package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"log"
	"meetup-graphql/core"
	"meetup-graphql/graphql/exec"
	"meetup-graphql/graphql/middleware"

	"github.com/google/uuid"
)

// AddUser is the resolver for the addUser field.
func (r *mutationResolver) AddUser(ctx context.Context, input *core.NewUser) (*core.User, error) {
	user := core.User{
		UserId:   uuid.New(),
		Username: input.Username,
		Email:    input.Email,
	}

	r.users = append(r.users, user)
	return &user, nil
}

// Meetups is the resolver for the meetups field.
func (r *queryResolver) Meetups(ctx context.Context) ([]core.Meetup, error) {
	panic(fmt.Errorf("not implemented: Meetups - meetups"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]core.User, error) {
	gc, err := middleware.GinContextFromContext(ctx)
	if err != nil {
		return nil, err
	}

	log.Println("IP user: ", gc.ClientIP())
	log.Println("User agent: ", gc.GetHeader("User-Agent"))
	return r.users, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*core.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// UserID is the resolver for the userId field.
func (r *userResolver) UserID(ctx context.Context, obj *core.User) (string, error) {
	panic(fmt.Errorf("not implemented: UserID - userId"))
}

// Mutation returns exec.MutationResolver implementation.
func (r *Resolver) Mutation() exec.MutationResolver { return &mutationResolver{r} }

// Query returns exec.QueryResolver implementation.
func (r *Resolver) Query() exec.QueryResolver { return &queryResolver{r} }

// User returns exec.UserResolver implementation.
func (r *Resolver) User() exec.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
